DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES(
    ID INT GENERATED AWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    POWER TEXT NOT NULL
)


INSERT INTO TB_HEROES (NAME, POWER)
VALUES ('Batman', 'Money'), ('Superman', 'All'), ('Flash','Speed')

SELECT * FROM TB_HEROES
SELECT * FROM TB_HEROES WHERE NAME = 'Flash'

UPDATE TB_HEROES
SET POWER = 'Superpower'
WHERE NAME = 'Superman'


DELETE FROM TB_HEROES
WHERE ID = 3